# -----------------------------------------------------
# |         Plot System Terra - by Alps BTE
# -----------------------------------------------------
# | [Github Repo] https://github.com/AlpsBTE/Plot-System-Terra
# | [Config Documentation] https://github.com/AlpsBTE/Plot-System-Terra/wiki
# | [Contacts - Discord] R3tuxn#7169, Coppertine#1718
# -----------------------------------------------------

# Keep updated about newer versions
check-for-updates: true

# Enables special dev tools and features for development
# NOTE: Do not change if you do not know what you are doing
dev-mode: false


# -----------------------------------------------------
# | Supported database: MariaDB
# -----------------------------------------------------
database:
  url: jdbc:mariadb://adress:3306/
  dbname: plotsystem
  username: plotsystem
  password: minecraft


# -----------------------------------------------------
# | Formatting: Info/Error message outputs
# -----------------------------------------------------
message-prefix: §7§l>>
info-colour: §a
error-colour: §c


# NOTE: Do not change
config-version: 1.0