main: github.alpsbte.PlotSystemTerra
version: 1.0
api-version: 1.12.2
name: Plot-System-Terra
author: R3tuxn

commands:
  createplot:
    description: Create a new plot for the PlotSystem
    usage: /createplot
    permission: plotsystem.createplot