main: com.alpsbte.plotsystemterra.PlotSystemTerra
version: 2.0
api-version: 1.12.2
name: PlotSystem-Terra
author: R3tuxn, Coppertine
softdepend: [WorldEdit, HeadDatabase]

commands:
  createplot:
    description: Creates a new plot for the PlotSystem.
    usage: /createplot
    permission: plotsystem.createplot