name: Plot-System-Terra
version: '3.0'
main: com.alpsbte.plotsystemterra.PlotSystemTerra
api-version: '1.20'
softdepend: [FastAsyncWorldEdit, WorldGuard, HeadDatabase]

commands:
  createplot:
    description: Creates a new plot for the PlotSystem.
    usage: /createplot
    permission: plotsystem.createplot
  pasteplot:
    description: Pastes a plot manually with specific ID
    usage: /pasteplot <ID>
    permission: plotsystem.pasteplot
  plotsystemterra:
    description: Sends info about the plugin
    usage: /plotsystemterra